### ISSUE TITLE
Just a little Front end Issue

### ISSUE THREAD

**Issue by MarvinKeriaan** [flytegg/mcu-website#146] opened 2023-08-16 11:42 UTC
on some screens this dark color and text is very hard to see, i think making the color lighter would be better
![Frontend Issue](https://github.com/flytegg/mcu-website/assets/119436268/e40ea8a6-d531-4b70-8741-43fab77e3f69)

**Comment by Difluoride** [comment] 2023-08-25 20:45
Duplicate of #141

**Closed by Difluoride** 2023-08-25 20:45 UTC
Labels: Enhancement / Feature, Global
